### ISSUE TITLE
we can also add placement Preparation Resources for both Tech and non-tech domains.

### ISSUE THREAD

**Issue by sachin-duhan** [anishLearnsToCode/course-list#1]

**Comment by anishLearnsToCode** [comment]
Hey, @sachin-duhan26 this repository is solely focused on courses completed by @anishLearnsToCode and I think adding placement resorces here will be a little out of scope, although I think creating a repository for placement resources will be a great idea. 

So, how about I create a seperate repo soleley dedicatd to placement resources and make you the main contributor, you can make as many PR's as you want and add important links etc. (I'll merge them all 😃)
